#!/usr/bin/env python3
"""Generate the direction table (SPEC-1 §4) for every target language.

The table is emitted as u32 bit patterns rather than decimal literals so that
every language reconstructs byte-identical f32 values by construction. No
runtime sin()/cos() is involved anywhere in the project.

Run from the repo root:   python3 spec/tools/gen_dirtable.py
"""

from __future__ import annotations

import math
import pathlib
import struct
import sys

NDIR = 1440
ROOT = pathlib.Path(__file__).resolve().parents[2]

FNV_OFFSET = 0x811C9DC5
FNV_PRIME = 0x01000193


def f32_bits(x: float) -> int:
    """Round a Python float (f64) to f32 and return its LE bit pattern."""
    return struct.unpack("<I", struct.pack("<f", x))[0]


def sbfnv32(words) -> int:
    h = FNV_OFFSET
    for w in words:
        h = (h ^ w) & 0xFFFFFFFF
        h = (h * FNV_PRIME) & 0xFFFFFFFF
    return h


def build() -> tuple[list[int], list[int]]:
    cos_bits, sin_bits = [], []
    for d in range(NDIR):
        a = 2.0 * math.pi * d / NDIR
        cos_bits.append(f32_bits(math.cos(a)))
        sin_bits.append(f32_bits(math.sin(a)))
    return cos_bits, sin_bits


def rows(bits: list[int], per_line: int = 8) -> list[str]:
    out = []
    for i in range(0, len(bits), per_line):
        out.append("  " + " ".join(f"0x{b:08X}," for b in bits[i : i + per_line]))
    return out


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


BANNER = "GENERATED by spec/tools/gen_dirtable.py -- DO NOT EDIT"


def emit_c(cos_b, sin_b, table_hash):
    body = f"""/* {BANNER}
 * SPEC-1 section 4: quantised direction table, NDIR={NDIR}.
 * Stored as u32 bit patterns; bit-cast to f32 at startup.
 */
#ifndef SB_DIRTABLE_H
#define SB_DIRTABLE_H

#include <stdint.h>

#define SB_NDIR {NDIR}
#define SB_DIRTABLE_HASH 0x{table_hash:08X}u

static const uint32_t SB_COS_BITS[SB_NDIR] = {{
{chr(10).join(rows(cos_b))}
}};

static const uint32_t SB_SIN_BITS[SB_NDIR] = {{
{chr(10).join(rows(sin_b))}
}};

#endif /* SB_DIRTABLE_H */
"""
    write(ROOT / "impl" / "c" / "dirtable.h", body)


def emit_ts(cos_b, sin_b, table_hash):
    def arr(bits):
        return "\n".join(rows(bits, 8))

    body = f"""// {BANNER}
// SPEC-1 section 4: quantised direction table, NDIR={NDIR}.

export const NDIR = {NDIR};
export const DIRTABLE_HASH = 0x{table_hash:08X};

const COS_BITS = new Uint32Array([
{arr(cos_b)}
]);

const SIN_BITS = new Uint32Array([
{arr(sin_b)}
]);

/** Bit-cast the u32 patterns to f32 without going through decimal. */
function toF32(bits: Uint32Array): Float32Array {{
  return new Float32Array(bits.buffer, bits.byteOffset, bits.length);
}}

export const COS: Float32Array = toF32(COS_BITS);
export const SIN: Float32Array = toF32(SIN_BITS);
"""
    write(ROOT / "impl" / "ts" / "src" / "dirtable.ts", body)


def emit_bin(cos_b, sin_b):
    blob = struct.pack(f"<{NDIR}I", *cos_b) + struct.pack(f"<{NDIR}I", *sin_b)
    p = ROOT / "spec" / "data" / f"dirtable_{NDIR}.bin"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(blob)
    print(f"  wrote {p.relative_to(ROOT)} ({len(blob)} bytes)")


def main() -> int:
    cos_b, sin_b = build()
    table_hash = sbfnv32(cos_b + sin_b)
    print(f"NDIR={NDIR}  dirtable_hash=0x{table_hash:08X}")

    # Sanity: the four cardinal directions must be exact.
    assert struct.unpack("<f", struct.pack("<I", cos_b[0]))[0] == 1.0
    assert struct.unpack("<f", struct.pack("<I", sin_b[0]))[0] == 0.0
    assert struct.unpack("<f", struct.pack("<I", sin_b[NDIR // 4]))[0] == 1.0
    assert struct.unpack("<f", struct.pack("<I", cos_b[NDIR // 2]))[0] == -1.0

    emit_c(cos_b, sin_b, table_hash)
    emit_ts(cos_b, sin_b, table_hash)
    emit_bin(cos_b, sin_b)
    return 0


if __name__ == "__main__":
    sys.exit(main())
