#!/usr/bin/env bash
# slimebench C# build driver.
#
#   ./build.sh jit     tiered JIT with dynamic PGO -- what `dotnet run` does
#   ./build.sh tier1   TieredCompilation off: everything straight to tier 1
#   ./build.sh r2r     ReadyToRun -- AOT-compiled IL that the JIT may re-tier
#   ./build.sh aot     Native AOT: a static binary, no JIT, no runtime
#   ./build.sh aot-native  the same, told which CPU it will run on
#
# This is the reason the C# port exists. Every other language here is on one
# side of the JIT/AOT line and stays there; .NET compiles the *same source*
# both ways, so the difference between `jit` and `aot` is the value of runtime
# profile information and nothing else. All four must produce the same hashes.
#
# `r2r` is the interesting middle: the IL is compiled ahead of time, but the
# runtime is still present and may recompile a hot method with profile data.
#
# Output is build/<profile>/slimebench, mirroring every other target. For the
# JIT profiles that is a generated launcher applying the environment; for aot
# it is the native binary itself.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

PROFILE="${1:-jit}"
OUT="build/$PROFILE"
OBJ="obj/$PROFILE"
rm -rf "$OUT"
mkdir -p "$OUT"

# Separate intermediate directories per profile: msbuild caches aggressively
# and a ReadyToRun image left over from another profile is exactly the kind of
# stale artefact that turns a measurement into a transcript. They live under
# obj/ rather than beside it, because the SDK's source glob excludes obj/ by
# name and would otherwise compile one profile's generated AssemblyInfo.cs
# into the next.
# BaseOutputPath too, not just the intermediate one: `dotnet publish`
# otherwise also fills impl/csharp/bin/, and a blanket bin/ in .gitignore
# would swallow impl/rust/src/bin/, which is real source.
COMMON=(-c Release -o "$OUT/app" --nologo
        -p:BaseIntermediateOutputPath="$OBJ/obj/"
        -p:BaseOutputPath="$OBJ/bin/")

# Two launcher shapes. The JIT profiles run the managed dll through `dotnet`
# with the runtime knobs in the environment; r2r and aot publish their own
# native apphost, which resolves everything relative to its own directory and
# therefore must be exec'd where it was published rather than copied out.
launcher_dotnet() { # env-assignments...
  {
    echo '#!/usr/bin/env sh'
    echo "# GENERATED by impl/csharp/build.sh -- profile: $PROFILE"
    # `env` and not a bare assignment before exec: `exec VAR=v cmd` looks for
    # a program literally named "VAR=v".
    printf 'exec env %s dotnet "$(dirname "$0")/app/slimebench.dll" "$@"
' "$*"
  } > "$OUT/slimebench"
  chmod +x "$OUT/slimebench"
}

launcher_native() {
  {
    echo '#!/usr/bin/env sh'
    echo "# GENERATED by impl/csharp/build.sh -- profile: $PROFILE"
    printf 'exec "$(dirname "$0")/app/slimebench" "$@"
'
  } > "$OUT/slimebench"
  chmod +x "$OUT/slimebench"
}

case "$PROFILE" in
  jit)
    dotnet publish "${COMMON[@]}" >/dev/null
    launcher_dotnet
    ;;
  tier1)
    dotnet publish "${COMMON[@]}" >/dev/null
    # TieredCompilation=0 sends every method straight to the optimising JIT,
    # so there is no quick tier-0 phase to climb out of. It also disables
    # dynamic PGO, which exists only to feed the re-tiering.
    launcher_dotnet DOTNET_TieredCompilation=0
    ;;
  r2r)
    dotnet publish "${COMMON[@]}" -r linux-x64 --self-contained true       -p:PublishReadyToRun=true >/dev/null
    launcher_native
    ;;
  aot)
    dotnet publish "${COMMON[@]}" -r linux-x64 -p:PublishAot=true       -p:InvariantGlobalization=true >/dev/null
    launcher_native
    ;;
  aot-native)
    # Native AOT compiles for the x64 *baseline* by default -- SSE2, so
    # Vector<float>.Count is 4 and Vector512.IsHardwareAccelerated is false,
    # even on a machine with AVX-512. The JIT has no such problem: it sees the
    # CPU it is running on. IlcInstructionSet is the way to tell the AOT
    # compiler, at the cost of a binary that no longer runs anywhere.
    #
    # This profile exists because the difference is a class V result: whether
    # ahead-of-time compilation keeps up with a JIT turns out to depend on
    # whether anyone remembered this flag.
    dotnet publish "${COMMON[@]}" -r linux-x64 -p:PublishAot=true       -p:InvariantGlobalization=true -p:IlcInstructionSet=native >/dev/null
    launcher_native
    ;;
  *) echo "unknown profile '$PROFILE'" >&2; exit 2 ;;
esac

echo "built $OUT/slimebench (profile $PROFILE)"
