#!/usr/bin/env bash
# slimebench Java build driver.
#
#   ./build.sh default   tiered compilation -- what `java Foo` actually does
#   ./build.sh c2        -XX:-TieredCompilation, C2 only, no C1 ramp
#   ./build.sh int       -Xint, interpreter only, no JIT at all
#
# Java's interesting axis is not the compiler, it is the runtime: javac emits
# the same bytecode either way and the JVM decides what becomes machine code
# and when. So a "profile" here is a set of JVM flags, and build.sh writes a
# launcher into build/<profile>/slimebench that applies them. Every other
# target in bench/targets.toml is a binary at that path; this makes Java one
# too, instead of teaching the harness about java -cp.
#
# `int` is not a serious configuration. It is here because it prices the JVM
# interpreter against CPython's on the identical algorithm shape, which is the
# comparison RESULTS section 2 makes for numba and could not make for anything
# with a JIT that cannot be switched off.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

PROFILE="${1:-default}"
JVM_FLAGS=()
case "$PROFILE" in
  default) ;;
  c2)  JVM_FLAGS=(-XX:-TieredCompilation) ;;
  int) JVM_FLAGS=(-Xint) ;;
  *) echo "unknown profile '$PROFILE'" >&2; exit 2 ;;
esac

OUT="build/$PROFILE"
mkdir -p "$OUT/classes"

# -Xlint:all with -Werror: a port that compiles with warnings is a port with an
# unread message in it. --release 17 rather than 21 because 17 is where strict
# floating point became the default (JEP 306) -- compiling against an older
# release than that would be claiming tier A the language did not guarantee.
javac --release 17 -Xlint:all -Werror -d "$OUT/classes" \
      src/Dirtable.java src/Sim.java src/Parallel.java src/Slimebench.java

cat > "$OUT/slimebench" <<EOF
#!/usr/bin/env sh
# GENERATED by impl/java/build.sh -- profile: $PROFILE
exec java ${JVM_FLAGS[*]:-} -cp "\$(dirname "\$0")/classes" Slimebench "\$@"
EOF
chmod +x "$OUT/slimebench"
echo "built $OUT/slimebench (profile $PROFILE)"
