#!/usr/bin/env bash
# slimebench Java build driver.
#
#   ./build.sh default   tiered compilation -- what `java Foo` actually does
#   ./build.sh c2        -XX:-TieredCompilation, C2 only, no C1 ramp
#   ./build.sh int       -Xint, interpreter only, no JIT at all
#
# Java's interesting axis is not the compiler, it is the runtime: javac emits
# the same bytecode either way and the JVM decides what becomes machine code
# and when. So a "profile" here is a set of JVM flags, and build.sh writes a
# launcher into build/<profile>/slimebench that applies them. Every other
# target in bench/targets.toml is a binary at that path; this makes Java one
# too, instead of teaching the harness about java -cp.
#
# `int` is not a serious configuration. It is here because it prices the JVM
# interpreter against CPython's on the identical algorithm shape, which is the
# comparison RESULTS section 2 makes for numba and could not make for anything
# with a JIT that cannot be switched off.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

PROFILE="${1:-default}"
JVM_FLAGS=()
case "$PROFILE" in
  default) ;;
  c2)  JVM_FLAGS=(-XX:-TieredCompilation) ;;
  int) JVM_FLAGS=(-Xint) ;;
  *) echo "unknown profile '$PROFILE'" >&2; exit 2 ;;
esac

OUT="build/$PROFILE"
mkdir -p "$OUT/classes"

# A port that compiles with warnings is a port with an unread message in it,
# so the rule is still "no warnings" -- but it cannot be spelled -Werror here.
# javac emits
#     warning: using incubating module(s): jdk.incubator.vector
# for every build that touches the Vector API, and there is no -Xlint key to
# switch that off; it is not a lint warning. So the output is captured and
# anything that is *not* that line fails the build.
#
# -source/-target 17 rather than --release 17, because --release cannot be
# combined with --add-modules for an incubator module -- one is not part of any
# release image. 17 is where strict floating point became the default (JEP
# 306), and compiling against anything older would be claiming a tier A the
# language did not guarantee. -Xlint:all,-options because -source/-target
# without --release warns about exactly that substitution.
#
# `|| rc=$?` and `|| true` are not decoration: this runs under `set -e`, javac
# is expected to be able to fail, and `grep -c` exits 1 when the count is zero.
# Without them the script dies silently before printing the reason.
log=$(mktemp)
rc=0
javac -source 17 -target 17 -Xlint:all,-options \
      --add-modules jdk.incubator.vector -d "$OUT/classes" \
      src/Dirtable.java src/Sim.java src/Parallel.java src/Simd.java \
      src/Slimebench.java 2>"$log" || rc=$?
grep -vE 'incubating module|^[0-9]+ warning' "$log" >&2 || true
other=$(grep -cvE 'incubating module|^[0-9]+ warning|^$' "$log" || true)
rm -f "$log"
if [ "$rc" -ne 0 ] || [ "$other" -ne 0 ]; then
  echo "javac failed (rc=$rc, $other unexpected diagnostics)" >&2
  exit 1
fi

cat > "$OUT/slimebench" <<EOF
#!/usr/bin/env sh
# GENERATED by impl/java/build.sh -- profile: $PROFILE
exec java --add-modules jdk.incubator.vector ${JVM_FLAGS[*]:-} \
  -cp "\$(dirname "\$0")/classes" Slimebench "\$@"
EOF
chmod +x "$OUT/slimebench"
echo "built $OUT/slimebench (profile $PROFILE)"
