#!/usr/bin/env python3
"""slimebench -- numpy implementation of SPEC-1 (conformance tier A, deferred only).

Everything is float32/uint32 arrays, so the arithmetic really is f32 and this
target is bit-exact with the C reference.

## Why this target cannot do --update serial

SPEC-1's `serial` mode requires agent i to see the deposit made by agent i-1
within the same tick. That is a sequential data dependency through the grid,
and no amount of vectorisation expresses it: `grid[idx] += deposit` with a
duplicated index does not even accumulate correctly in numpy, let alone feed
the result back into the sensing of a later element of the same batch.

`deferred` mode has no such dependency, and `np.add.at` accumulates duplicate
indices unbuffered and in index order -- which is exactly the order SPEC-1
prescribes. So this target implements `deferred` and rejects `serial` with a
clear error rather than silently computing something else.

That restriction is a finding about the programming model, not a defect, and
it is why the benchmark registry marks this target deferred-only.
"""

from __future__ import annotations

import sys
import time

import numpy as np

sys.path.insert(0, __file__.rsplit("/", 1)[0])

from slimebench import common
from slimebench.dirtable import COS_BITS, NDIR, SIN_BITS

FNV_OFFSET = np.uint32(0x811C9DC5)
FNV_PRIME = np.uint32(0x01000193)


def _u32(x) -> np.uint32:
    return np.uint32(x & 0xFFFFFFFF)


def splitmix32_vec(state: np.ndarray) -> np.ndarray:
    """In-place SplitMix32 over a uint32 array; returns the outputs."""
    state += np.uint32(0x9E3779B9)
    z = state.copy()
    z ^= z >> np.uint32(16)
    z *= np.uint32(0x21F0AAAD)
    z ^= z >> np.uint32(15)
    z *= np.uint32(0x735A2D97)
    return z ^ (z >> np.uint32(15))


def rotl32_vec(x: np.ndarray, k: int) -> np.ndarray:
    return (x << np.uint32(k)) | (x >> np.uint32(32 - k))


def xoshiro128pp_vec(s: np.ndarray, sel: np.ndarray | None = None) -> np.ndarray:
    """xoshiro128++ advanced for the selected rows of `s` (shape [N, 4]).

    `sel` is a boolean mask: SPEC-1 only consumes randomness in the dead-end
    branch, so only those agents' streams may advance. Advancing all of them
    would silently desynchronise from every other implementation.
    """
    v = s if sel is None else s[sel]
    s0, s1, s2, s3 = v[:, 0].copy(), v[:, 1].copy(), v[:, 2].copy(), v[:, 3].copy()

    result = rotl32_vec(s0 + s3, 7) + s0
    t = s1 << np.uint32(9)
    s2 ^= s0
    s3 ^= s1
    s1 ^= s2
    s0 ^= s3
    s2 ^= t
    s3 = rotl32_vec(s3, 11)

    v[:, 0], v[:, 1], v[:, 2], v[:, 3] = s0, s1, s2, s3
    if sel is not None:
        s[sel] = v
    return result


class Sim:
    def __init__(self, cfg: common.Config, bufs: dict | None = None,
                 do_init: bool = True):
        common.check_pow2(cfg)
        common.normalize_f32(cfg)
        if cfg.update != "deferred":
            sys.stderr.write(
                "error: the numpy target implements --update deferred only.\n"
                "       SPEC-1 'serial' has a sequential dependency through the\n"
                "       grid that cannot be vectorised; see the module docstring.\n")
            sys.exit(3)

        self.cfg = cfg
        self.log2w = cfg.width.bit_length() - 1
        self.xmask = np.uint32(cfg.width - 1)
        self.ymask = np.uint32(cfg.height - 1)

        cells = cfg.width * cfg.height
        if bufs is None:
            self.grid = np.zeros(cells, dtype=np.float32)
            self.scratch = np.zeros(cells, dtype=np.float32)
            self.dep = np.zeros(cells, dtype=np.float32)
            self.ax = np.zeros(cfg.agents, dtype=np.float32)
            self.ay = np.zeros(cfg.agents, dtype=np.float32)
            self.adir = np.zeros(cfg.agents, dtype=np.int32)
            self.arng = np.zeros((cfg.agents, 4), dtype=np.uint32)
        else:
            # Class P: views over one multiprocessing.shared_memory block, so
            # every worker process sees the same grid. See slimebench_mp.py.
            for k in ("grid", "scratch", "dep", "ax", "ay", "adir", "arng"):
                setattr(self, k, bufs[k])

        self.cos = np.frombuffer(np.array(COS_BITS, dtype=np.uint32).tobytes(),
                                 dtype=np.float32)
        self.sin = np.frombuffer(np.array(SIN_BITS, dtype=np.uint32).tobytes(),
                                 dtype=np.float32)
        self._fw = np.float32(cfg.width)
        self._fh = np.float32(cfg.height)

        self.ns_agents = 0
        self.ns_diffuse = 0
        if do_init:
            self._init_state()

    def _init_state(self) -> None:
        cfg = self.cfg

        # Grid: a single sequential SplitMix32 stream. Vectorising this would
        # change the value sequence, so it is generated by iterating the scalar
        # recurrence -- once, at startup.
        sm = cfg.seed ^ 0x5BF03635
        out = np.empty(self.grid.size, dtype=np.uint32)
        mask = 0xFFFFFFFF
        for i in range(out.size):
            sm = (sm + 0x9E3779B9) & mask
            z = sm
            z = ((z ^ (z >> 16)) * 0x21F0AAAD) & mask
            z = ((z ^ (z >> 15)) * 0x735A2D97) & mask
            out[i] = z ^ (z >> 15)
        self.grid[:] = (out >> np.uint32(8)).astype(np.float32) / np.float32(16777216.0)
        self.grid *= np.float32(100.0)

        # Agents: independent streams, so this part vectorises exactly.
        n = cfg.agents
        idx = np.arange(1, n + 1, dtype=np.uint32)
        state = (np.uint32(cfg.seed) + np.uint32(0x9E3779B9) * idx).astype(np.uint32)
        for k in range(4):
            self.arng[:, k] = splitmix32_vec(state)
        allzero = (self.arng[:, 0] | self.arng[:, 1] |
                   self.arng[:, 2] | self.arng[:, 3]) == 0
        self.arng[allzero, 0] = 1

        r1 = xoshiro128pp_vec(self.arng)
        r2 = xoshiro128pp_vec(self.arng)
        r3 = xoshiro128pp_vec(self.arng)
        inv = np.float32(1.0) / np.float32(16777216.0)
        self.ax[:] = ((r1 >> np.uint32(8)).astype(np.float32) * inv) * np.float32(cfg.width)
        self.ay[:] = ((r2 >> np.uint32(8)).astype(np.float32) * inv) * np.float32(cfg.height)
        self.adir[:] = (r3 % np.uint32(NDIR)).astype(np.int32)

    # ---- passes ----------------------------------------------------------

    def _wrapf(self, v: np.ndarray, m: np.float32) -> np.ndarray:
        np.add(v, m, out=v, where=v < np.float32(0.0))
        np.subtract(v, m, out=v, where=v >= m)
        return v

    def _sense(self, x: np.ndarray, y: np.ndarray, d: np.ndarray) -> np.ndarray:
        sx = self._wrapf(x + self.cos[d] * self.cfg.sensor_dist, self._fw)
        sy = self._wrapf(y + self.sin[d] * self.cfg.sensor_dist, self._fh)
        idx = ((sy.astype(np.uint32) & self.ymask) << np.uint32(self.log2w)) | \
              (sx.astype(np.uint32) & self.xmask)
        return self.grid[idx]

    def tick(self) -> None:
        t0 = time.perf_counter_ns()
        self.agent_range(0, self.cfg.agents)
        t1 = time.perf_counter_ns()

        self.merge_rows(0, self.cfg.height)
        self.diffuse_rows(0, self.cfg.height)
        self.swap_buffers()

        t2 = time.perf_counter_ns()
        self.ns_agents += t1 - t0
        self.ns_diffuse += t2 - t1

    def swap_buffers(self) -> None:
        self.grid, self.scratch = self.scratch, self.grid

    def merge_rows(self, y0: int, y1: int) -> None:
        """Fold `dep` into `grid` over rows [y0, y1) and clear it."""
        lo = y0 << self.log2w
        hi = y1 << self.log2w
        self.grid[lo:hi] += self.dep[lo:hi]
        self.dep[lo:hi] = np.float32(0.0)

    def agent_range(self, lo: int, hi: int, aidx: np.ndarray | None = None) -> None:
        """SPEC-1 section 5.3 over agents [lo, hi).

        With `aidx` the deposit is *not* applied; the target cell is written to
        `aidx[lo:hi]` for a later phase to apply in a chosen order. That is the
        only thing the multi-process caller does differently -- everything
        above it stays identical, or the parallel run stops being the same
        simulation.

        Every write goes back into the caller's arrays in place: under class P
        those are views onto shared memory, and rebinding `self.ax` would leave
        the other processes looking at the old values.
        """
        cfg = self.cfg
        ndir = np.int32(NDIR)
        ss = np.int32(cfg.sensor_steps)
        rs = np.int32(cfg.rot_steps)

        d = self.adir[lo:hi]
        x, y = self.ax[lo:hi].copy(), self.ay[lo:hi].copy()
        arng = self.arng[lo:hi]

        dl = (d - ss + ndir) % ndir
        dr = (d + ss) % ndir

        fl = self._sense(x, y, dl)
        fc = self._sense(x, y, d)
        fr = self._sense(x, y, dr)

        straight = (fc >= fl) & (fc >= fr)
        deadend = (~straight) & (fc < fl) & (fc < fr)
        left = (~straight) & (~deadend) & (fl > fr)
        right = ~(straight | deadend | left)

        # Only dead-end agents consume randomness (SPEC-1 section 5.3).
        newd = d.copy()
        if deadend.any():
            bits = xoshiro128pp_vec(arng, deadend) & np.uint32(1)
            sub = d[deadend]
            turn_right = bits != 0
            sub = np.where(turn_right, (sub + rs) % ndir, (sub - rs + ndir) % ndir)
            newd[deadend] = sub
        newd[left] = (d[left] - rs + ndir) % ndir
        newd[right] = (d[right] + rs) % ndir
        self.adir[lo:hi] = newd

        x = self._wrapf(x + self.cos[newd] * cfg.step, self._fw)
        y = self._wrapf(y + self.sin[newd] * cfg.step, self._fh)
        self.ax[lo:hi] = x
        self.ay[lo:hi] = y

        idx = ((y.astype(np.uint32) & self.ymask) << np.uint32(self.log2w)) | \
              (x.astype(np.uint32) & self.xmask)
        if aidx is not None:
            aidx[lo:hi] = idx
            return
        # Unbuffered, in index order: matches SPEC-1's per-agent accumulation.
        np.add.at(self.dep, idx, np.float32(cfg.deposit))

    def diffuse_rows(self, y0: int, y1: int) -> None:
        """SPEC-1 section 5.4 over rows [y0, y1), writing into `scratch`.

        Output cells are independent, so splitting the row range across
        processes is unconditionally bit-identical. The rows are gathered by
        index rather than by np.roll on the whole grid, because a row block
        needs its two neighbouring rows and those may wrap.
        """
        cfg = self.cfg
        h, w = cfg.height, cfg.width
        g = self.grid.reshape(h, w)

        rows = np.arange(y0, y1)
        up = g[(rows - 1) % h]
        mid = g[rows]
        dn = g[(rows + 1) % h]

        # Summation order is normative; each term is applied in sequence.
        acc = np.roll(up, 1, axis=1)
        acc = acc + up
        acc = acc + np.roll(up, -1, axis=1)
        acc = acc + np.roll(mid, 1, axis=1)
        acc = acc + np.float32(4.0) * mid
        acc = acc + np.roll(mid, -1, axis=1)
        acc = acc + np.roll(dn, 1, axis=1)
        acc = acc + dn
        acc = acc + np.roll(dn, -1, axis=1)

        out = (acc / np.float32(12.0)) * np.float32(cfg.decay)
        self.scratch.reshape(h, w)[y0:y1] = out

    # ---- checksums -------------------------------------------------------

    def hash_grid(self) -> int:
        return _fnv_words(self.grid.view(np.uint32))

    def hash_agents(self) -> int:
        inter = np.empty(self.cfg.agents * 3, dtype=np.uint32)
        inter[0::3] = self.ax.view(np.uint32)
        inter[1::3] = self.ay.view(np.uint32)
        inter[2::3] = self.adir.astype(np.uint32)
        return _fnv_words(inter)


def _fnv_words(words: np.ndarray) -> int:
    """SB-FNV32 over u32 words.

    Inherently sequential (each step feeds the next), so this stays a Python
    loop over a bytes view rather than pretending to vectorise.
    """
    h = 0x811C9DC5
    prime = 0x01000193
    mask = 0xFFFFFFFF
    for w in words.tolist():
        h = ((h ^ w) * prime) & mask
    return h


def dirtable_hash() -> int:
    return _fnv_words(np.array(list(COS_BITS) + list(SIN_BITS), dtype=np.uint32))


def main() -> int:
    o = common.parse_args()
    cfg = o.cfg

    if cfg.threads > 1:
        # Class P. Processes, not threads -- see slimebench_mp.py for why.
        import slimebench_mp
        sim, ms_total, tick_ms = slimebench_mp.run_parallel(
            cfg, cfg.threads, cfg.deposit_reduce, cfg.warmup, cfg.ticks,
            backend=cfg.mp_backend)
        cls = "P"
        # The variant has to name the carrier as well as the strategy: on a
        # free-threaded build these are two different measurements.
        gil = "gil" if slimebench_mp.gil_enabled() else "nogil"
        variant = f"{cfg.deposit_reduce}+{cfg.mp_backend[:4]}-{gil}"
    else:
        cls, variant = "S", "numpy"
        sim = Sim(cfg)

        for _ in range(cfg.warmup):
            sim.tick()
        sim.ns_agents = sim.ns_diffuse = 0

        tick_ms: list[float] = []
        t_start = time.perf_counter_ns()
        for t in range(cfg.ticks):
            a = time.perf_counter_ns()
            sim.tick()
            tick_ms.append((time.perf_counter_ns() - a) / 1e6)
            if cfg.hash_every and (t + 1) % cfg.hash_every == 0:
                sys.stderr.write(f"tick {t+1} grid=0x{sim.hash_grid():08X} "
                                 f"agents=0x{sim.hash_agents():08X}\n")
        ms_total = (time.perf_counter_ns() - t_start) / 1e6

    if o.dump_grid:
        sim.grid.tofile(o.dump_grid)

    if o.want_json:
        print(common.result_json(
            cfg, impl="python", backend="numpy", cls=cls, variant=variant,
            grid_hash=sim.hash_grid(), agent_hash=sim.hash_agents(),
            dirtable_hash=dirtable_hash(), ms_total=ms_total,
            ms_agents=sim.ns_agents / 1e6, ms_diffuse=sim.ns_diffuse / 1e6,
            tick_ms=tick_ms))
    else:
        common.print_human(cfg, variant, sim.hash_grid(), sim.hash_agents(),
                           ms_total, sim.ns_agents / 1e6, sim.ns_diffuse / 1e6,
                           cfg.ticks)
    return 0


if __name__ == "__main__":
    sys.exit(main())
